### PR TITLE
Flexible transaction split

### PR DESCRIPTION
**Pull request by kameronton**
This branch adds support of django-money and flexible transaction split. As far as I see, resolution algorithm still works. 

Also, I have added a small bunch of code that do 'almost-even' splitting at stage of creating a transaction.

Also, there is a validation of a distribution: small transactions' sum should be equal to a whole amount of a transaction.

Any suggestions for tests?

### CODE REVIEW

**Comment by kameronton** [comment]
@Kessaye , can you, please, take a look on resolution.py ? I don't really understand what is the difference between branches. You can check what I've changed here: 
86198d3

**Comment by Kessaye** [comment]
Hello @kameronton can you explain to me a bit more what is happening here so I can understand much faster what to check and how to solve it please?
Thank you.

**Comment by kameronton** [comment]
(click 'resolve conflicts' to see)

**Comment by Kessaye** [comment]
@kameronton the version of resolution in master is indeed the right one: 
I have cleaned the code and added some comments; I have also resolved a Bug.
Right now I am no more changing the resolution algorithm but I will start changing for the moment the Transaction model to add the currency part. 
I think that solving this conflict would be by copying using the version on master and changing this small element you made but I prefer not to work on your branch so that I won't break anything!
Can you do it please :) ?

**Comment by kameronton** [comment]
Okay, tests are failing, I'm trying to resolve that

**Pull request merged**
